###############################################################################
# @author:      Carl-Eric Wegner, PhD
# @affiliation: Biomics Group - Chair of Bioinorganic Chemistry
#               Heinrich Heine University Düsseldorf
#
# @contact      carl-eric.wegner@hhu.de
#               https://biomics.hhu.de
#               https://github.com/wegner
#               https://exploringmicrobes.science
###############################################################################

###############################################################################
# needed packages
###############################################################################
import pandas as pd
import os

###############################################################################
# specify the config file
###############################################################################
configfile: "config/config.yaml"

###############################################################################
# needed resources
###############################################################################
# Notes:
# Right now QC and trimming are done using fastQC and bbduk. Using fastp in
# future is more efficient, as it combines QC and trimming. This would save
# jobs (=time), and reduce the number of needed rules. fastQC is also not
# ideal in terms of multithreading.
#
# fastp needs no external adapter/contaminant database. The file specified
# here is shipped with bbduk.
#
# Right now, the legacy databases of SortMeRNA 2.1b are used. This is not super
# smart, given that we deal with single organisms here. The database could be
# slimmed down signficicantly, or one could simply use the rRNA gene sequences 
# of the respectice organism.
#
# Checking out more recent tools for detecting rRNA-derived sequences could
# be also an option, e.g. ribodetector.
REF_GENOME       = config["MAPPING"]["ref_genome"]
ADAPTER          = config["adapter-file"]
SILVA_16S_BAC_DB = os.path.abspath(config["SORTMERNA"]["silva_16s_bac_db"])
SILVA_23S_BAC_DB = os.path.abspath(config["SORTMERNA"]["silva_23s_bac_db"])

# Note:
# Originally, the pipeline was solely written for Beijerinckiaceae bacterium
# RH AL1, and the .saf file needed by featureCounts was provided, to make 
# the pipeline more flexible, a script was added to generate the .saf file
# as needed (= if none is provided). We check here if any is given, .saf or
# .gff3 file.
_ref_saf  = config["COUNTING"].get("ref_saf")  or ""
_ref_gff3 = config["COUNTING"].get("ref_gff3") or ""

if _ref_saf:
    REF_SAF  = _ref_saf
    REF_GFF3 = None
elif _ref_gff3:
    REF_GFF3 = _ref_gff3
    REF_SAF  = os.path.splitext(REF_GFF3)[0] + ".saf"
else:
    raise ValueError(
        "config[COUNTING] must either specify ref_saf (pre-built .saf,"
        "user-provided) or ref_gff3 (.saf will be generated on-the-fly)"
        "»» neither was found (not good!) ««"
    )

###############################################################################
# relevant parameters input files
###############################################################################
# Note:
# PAIRS was modified, to allow the processing of single-end data, the GTL @HHU
# tends to provide single-end data from testsequencing.
# 
# Took me a while to troubleshoot that the first time :-/
r1_suffix = config["Fastq"]["suffix_R1"]
r2_suffix = config["Fastq"]["suffix_R2"]
IS_PAIRED = config["Fastq"].get("paired", True)
PAIRS = [r1_suffix, r2_suffix] if IS_PAIRED else [r1_suffix]

###############################################################################
# read sample names from samples.tsv
###############################################################################
# Note:
# We use the power of pandas here to read the sample names.
# In future, it is planned to make the samples.tsv file more relevant with 
# regard to providing more metadata.
SAMPLES = pd.read_table(config["sample-file"], header=0, sep="\t", index_col=0)
raw_data_dir = config["rawdata-dir"]

###############################################################################

rule all:
    input:
        # aggregated QC report
        "results/00_QC/multiqc_report.html",
        # per-sample read and base count summary
        "results/00_QC/read_stats.tsv",
        # counting
        "results/04_COUNTS/readcounts_featureCounts.txt",
        # mapping
        expand("results/03_MAPPED/{sample}_mapped_sorted.bam", sample=SAMPLES.index),
        # filtering
        expand("results/02_FILTERED/{sample}_mRNA_{pair}.fastq", sample=SAMPLES.index, pair=PAIRS),
        # trimming
        expand("results/01_TRIMMED/{sample}_trimmed_{pair}.fastq", sample=SAMPLES.index, pair=PAIRS),
        # QC
        expand("logs/fastqc/raw/{sample}_{pair}_fastqc.html", sample=SAMPLES.index, pair=PAIRS),
        expand("logs/fastqc/trimmed/{sample}_trimmed_{pair}_fastqc.html", sample=SAMPLES.index, pair=PAIRS),

###############################################################################
# needed rules
###############################################################################
include: "rules/qc.smk"
include: "rules/sortmerna.smk"
include: "rules/mapping.smk"
include: "rules/featurecounts.smk"
